import type { Metadata } from 'next';
import { Inter, DM_Serif_Display } from 'next/font/google';
import './globals.css';

const inter = Inter({
	subsets: ['latin'],
	weight: 'variable',
	variable: '--font-body',
});

const dmSerifDisplay = DM_Serif_Display({
	subsets: ['latin'],
	weight: '400',
	variable: '--font-heading',
});

export const metadata: Metadata = {
	title:
		'DinnerDibs | Discover and order fresh homemade food by your favorite chefs!',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${inter.variable} ${dmSerifDisplay.variable} antialiased`}
		>
			<body className={`flex min-h-full flex-col`}>{children}</body>
		</html>
	);
}
