import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({
	subsets: ['latin'],
	weight: 'variable',
});

export const metadata: Metadata = {
	title:
		'DinnerDibs | Discover and order fresh homemade food by your favorite chefs!',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`antialiased`}
		>
			<body className={`${inter.className} min-h-full flex flex-col`}>
				{children}
			</body>
		</html>
	);
}
